"""empty message

Revision ID: 8821b5a2aa66
Revises: a5e7f554684b
Create Date: 2017-05-25 08:57:22.577123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8821b5a2aa66'
down_revision = 'a5e7f554684b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'state',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'state',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
